---
- name: Start Flask Web App
  hosts: g1
  become: yes

  vars:
    flask_app_directory: /home/centos/jenkins-ansible-flask-1
    flask_app_repo: https://github.com/kesienaf/jenkins-ansible-flask-1.git

  tasks:
    - name: Start App
      command: python3 /home/centos/jenkins-ansible-flask-1/app.py 
...