---
- name: Start Flask Web App
  hosts: g1
  become: yes

  tasks:
    - name: Start App
      command: "nohup python3 /home/centos/jenkins-ansible-flask-1/app.py &"
      async: 60
      poll: 0
    
    - name: Delay stop of flask app
      pause:
        seconds: 60
    
    - name: Find and Kill Flask Process
      shell: "pkill -f 'app.py'"
      ignore_errors: yes  # Ignore errors if the process is not found
    
    - name: Wait for Process to be Killed
      pause:
        seconds: 5  # Adjust the duration as needed
...