---
- name: Start Flask Web App
  hosts: g1
  become: yes

  vars:
    flask_app_directory: /home/centos/jenkins-ansible-flask-1
    flask_app_repo: https://github.com/kesienaf/jenkins-ansible-flask-1.git

  tasks:
    - name: Activate virtual environment
      command: "/bin/bash -c 'source {{ flask_app_directory }}/venv/bin/activate'"
      become: yes

    - name: Create Nginx sites-enabled directory
      file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Create symbolic link for Nginx configuration
      file:
        src: /etc/nginx/sites-available/flask_app
        dest: /etc/nginx/sites-enabled/flask_app
        state: link
      notify:
        - restart nginx

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Configure Supervisor
      template:
        src: supervisor.conf.j2
        dest: /etc/supervisor/conf.d/flask_app.conf
      notify:
        - restart supervisor
    
    - name: Start App
      command: python3 app.py 
  
  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted
    
    - name: restart supervisor
      service:
        name: supervisord # Use 'supervisord' as the service name
        state: restarted
...