---
- name: Start Flask Web App
  hosts: g1
  become: yes

  tasks:
    - name: Start Flask App
      command: "nohup python3 /home/centos/jenkins-ansible-flask-1/app.py &"
      async: 60
      poll: 0
      become_user: "{{ ansible_user }}"
      when: ansible_distribution == 'CentOS'

    - name: Start Flask App
      command: "nohup python3 /home/ubuntu/jenkins-ansible-flask-1/app.py &"
      async: 60
      poll: 0
      become_user: "{{ ansible_user }}"
      when: ansible_distribution == 'Ubuntu'

    - name: Delay stopping Flask app
      pause:
        seconds: 60
...